<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsqe8Mo\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsqe8Mo/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDsqe8Mo.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDsqe8Mo\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDsqe8Mo\App_KernelProdContainer([
    'container.build_hash' => 'Dsqe8Mo',
    'container.build_id' => '8a5f3359',
    'container.build_time' => 1670916532,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsqe8Mo');
